In [70]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)*5
c= np.arange(10, 51, 1)

print("Tablica zer: ", end="")
print(a, "\n")
print("Tablica piątek: ", end="")
print(b, "\n")
print("Tablica 10-50: ", end="")
print(c, "\n")


d =  np.arange(0, 9).reshape(3,3)
print("Macierz 3x3: ")
print(d, "\n")

e = np.eye(3)
print("Macierz jednostkowa 3x3: ")
print(e, "\n")

mu, sigma = 0, 0.1
f = np.random.normal(mu, sigma, 25).reshape(5,5)
print("Macierz 5x5: ")
print(f, "\n")

g =  np.arange(0.01, 1.01, 0.01).reshape(10,10)
print("Macierz 10x10: ")
print(g, "\n")

h = np.arange(0, 1.05, 0.05)
print("Tablica 20 liniowo rozłożonych liczb: ")
print(h, "\n")

i = np.random.randint(1, 25, 25)
i = i.reshape(5, 5)
print("Macierz 5x5: ")
print(i, "\n")

print("Suma: ", end='')
print(np.sum(i))

print("Średnia: ", end='')
print(np.mean(i))

print("Standardowa dewiacja: ", end='')
print(np.std(i))

print("Suma w każdej z kolumn: ", end='')
print(i.sum(axis=0), "\n")

j = np.random.randint(100, size=(5, 5))
print("Macierz 5x5: ")
print(j, "\n")

print("Mediana: ", end='')
print(np.median(j))

print("Najmiejsza: ", end='')
print(np.min(j))

print("Największa: ", end='')
print(np.max(j), "\n")

k = np.random.randint(100, size=(4, 6))
print("Macierz 4x6: ")
print(k, "\n")
print("Macierz 6x4: ")
print(np.transpose(k), "\n")


l = np.random.randint(10, size=(5,7))
m = np.random.randint(10, size=(5, 7))
print("Macierz l 5x7: ")
print(l, "\n")
print("Macierz m 5x7: ")
print(m, "\n")
print("Suma macierzy l i m : ")
print(l.__add__(m), "\n")

n = np.random.randint(10, size=(5,9))
o = np.random.randint(10, size=(9, 6))
print("Macierz n 5x9: ")
print(n, "\n")
print("Macierz o 9x6: ")
print(o, "\n")
print("Macierz n*o pierwszym sposobem: ")
print(np.matmul(n, o), "\n")
print("Macierz n*o drugim sposobem: ")
print(n.dot(o))




Tablica zer: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

Tablica piątek: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 

Tablica 10-50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50] 

Macierz 3x3: 
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

Macierz jednostkowa 3x3: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Macierz 5x5: 
[[ 0.08268589 -0.09123897 -0.15618559 -0.05099284  0.00360585]
 [-0.11098452 -0.05192657  0.00734795 -0.14834332  0.01440408]
 [ 0.09298029  0.16580746 -0.05112401  0.11455961 -0.07321063]
 [-0.01621547  0.0119667   0.08432435  0.08783087  0.00857395]
 [-0.04907032 -0.08231703  0.02441623  0.10893885  0.15353074]] 

Macierz 10x10: 
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0